###
POST http://localhost:3000/auth HTTP/1.1

###
POST http://localhost:3000/verify HTTP/1.1

paste jwt token from first post request here

###
GET http://localhost:3000/secured HTTP/1.1
Authorization: Bearer paste jwt token from first post request here